name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Download SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
        shell: bash

      - name: Configure SonarQube Scanner
        run: |
          echo "sonar.host.url=YOUR_SONARQUBE_SERVER_URL" > sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties
          echo "sonar.login=$SONAR_TOKEN" >> sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

      - name: Build and Analyze Go Project
        run: |
          go build
          sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
